### ISSUE TITLE
Is there a way to get Transaction History? (i.e. bonuses)

### ISSUE THREAD

**Issue by mikemilano** [Bitrue-exchange/Spot-official-api-docs#10]
The Bitrue UI shows transaction history at /assets/history. This includes Bonuses, or interest earned from the staking programs.

I'm wondering if this data is available through the API. I think it's available since 3rd party tax service providers show bonus transactions, but it's unclear how to access this data.

**Comment by Yoruichi** [comment]
Note this. And we'll provide API for that.

**Comment by cmaycocksgfa** [comment]
Hi there, thanks for an awesome project. Any update on when this will be available via API?  Thanks
