### ISSUE TITLE
Multiple ticker symbols

### ISSUE THREAD

**Issue by TJakubek** [Bitrue-exchange/Spot-official-api-docs#18]
I am trying to use the /api/v1/ticker/price endpoint with multiple symbols but do not know how to get it working. It works for one, but there is no information on how to use multiple symbols. 

Any tips?

**Comment by rulo96z** [comment]
I would love some solution on here I found my self with thee same problem.

**Comment by benry1** [comment]
You need to call the same api once for each symbol, I have not found a way to query N symbols. I've also found that this can be unreliable, and return blank responses ~25% of the time, so you may have to call multiple times for the same symbol.

Note that each call for a single symbol is Weight 1, and a call for all symbols is Weight 40. So, if you are checking 30+ symbols, it may be more weight-efficient to get All symbols at once, and filter the ones you don't need on the clientside. Calling for all symbols is also very reliable.

**Comment by TJakubek** [comment]
thanks for the answer, I think I will try with your suggestion. 

But in that case I suggest the documentation be changed so there is no suggestion that multiple symbols can be used
'Latest price for a symbol **or symbols.**'

**Comment by francesco-adamo** [comment]
Hi, I am trying to get data for all symbols at once too but a connection to `GET /api/v1/ticker/price `
returns` { code: -1102 msg: "Missing parameter." }`
How can you specify that you are requesting all symbols? Thanks

**Comment by TJakubek** [comment]
as stated above, noone has been able to get all symbols. Are you adding your api key to the request?

**Comment by francesco-adamo** [comment]
> as stated above, noone has been able to get all symbols. Are you adding your api key to the request?

I see, thanks! I thought from @benry1 answer that it was possible, with weight 40. But like you said so far I was not able to do it. I am not adding the API key information because the request is in the public section so it shouldn't be necessary. If I pass the `symbol` parameter it works well, but just for one specific symbol.

**Comment by RookieLongTIme** [comment]
how do you add api key to the request? i'm using fetch()
