### ISSUE TITLE
In historicalTrades not work parameter fromId

### ISSUE THREAD

**Issue by iLnaar** [Bitrue-exchange/Spot-official-api-docs#24]
Request example:

[https://www.bitrue.com/api/v1/historicalTrades?fromId=3836000&limit=10&symbol=BTCUSDT](https://www.bitrue.com/api/v1/historicalTrades?fromId=3836000&limit=10&symbol=BTCUSDT)

Whatever you specify parameter fromId , the latest data is still returned

**Comment by Yoruichi** [comment]
We noticed this issues and will fixed it soon.

**Comment by luckydziuba** [comment]
any hope?

**Comment by neilbirtles** [comment]
the same applies for the mytrades api. Means there is no way to get historic trade information from the API apart from the last 1000 trades for any given symbol pair

**Comment by Yoruichi** [comment]
Fixed
