### ISSUE TITLE
Get Empty Data

### ISSUE THREAD

**Issue by mefe-tr** [Bitrue-exchange/Spot-official-api-docs#31]
When I use "market/kline?symbol=NETUSDT&scale=1h" api command, sometimes I get empty data and this situation doesn't fix within 30 or 45minutes. 

**Sent Data** : https://www.bitrue.com/api/v1/market/kline?symbol=NETUSDT&scale=1h
**Get Data** : 
{
    "symbol": "NETUSDT",
    "scale": "KLINE_1H",
    "data": []
}

Can you help me?

Best regards,
Muhammet EFE

**Comment by Yoruichi** [comment]
Please use the domain in DOC. https://openapi.bitrue.com NOT www.bitrue.com.
And u will get the data u want.
