### ISSUE TITLE
Ambiguous rate limit

### ISSUE THREAD

**Issue by azizfcb** [Bitrue-exchange/Spot-official-api-docs#38]
Thanks for this doc.

I've been trying to fetch my trades, and I'm trying to understand what are the API rate limits.
I see that my trades endpoint weight is 5. But 5 what? That's not clear. Thanks for advance 😊

**Comment by neilbirtles** [comment]
The /api/v1/exchangeInfo end point gives total weights you're allowed in given time frames, weight 5 means each request uses up 5 if this allowance, weight 100 uses up 100 etc. So need to track different types of requests and how many you've done in the relevant time window

**Comment by azizfcb** [comment]
Thanks @neilbirtles 

That's my exact problem. Talking about fetching trades, where is this info in /exchangeinfo? Is it "general" (1500 weight per minute?)

Does this mean that I'm allowed to do 300 (1500/5) requests per minute? Thanks for helping me.

**Comment by azizfcb** [comment]
And by the way, I think there's a bug. When I try to run two requets (fetch my trades) in a very short time frame (under 2 seconds) the API returns -1102 timestamp illegal argument exception (with 412 status code) instead if a rate limit error (429)

**Comment by shyamvyas5** [comment]
Hi @azizfcb I'm getting the same `{"code":-1102,"msg":"timestamp IllegalArgumentException.","data":null}` while making a curl request, were you able to circumvent this issue?
